### ISSUE TITLE
[Bug]: Synchronization error: request failed, status 403 at eval

### ISSUE THREAD

**Issue by lyiton** [sboesen/remotely-sync#64]
### What happened?

![PixPin_2023-12-13_10-40-09](https://github.com/sboesen/remotely-sync/assets/76651858/4cd50134-f54a-4790-9983-5654ae11269b)
I took notes normally, but automatic synchronization failed. Then I turned it off, and manual synchronization still failed. The error report is as shown in the picture, I don't know what caused it. It shouldn't be caused by the S3 service, because I can access the bucket normally.

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.4.27

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
I haven't seen this myself - is it possible the S3 access key has been blocked?

I found this [thread](https://stackoverflow.com/questions/26691286/amazon-s3-bucket-returning-403-forbidden) that suggests clock skew could be a factor in 403 errors with S3. Is your computer's clock time set automatically?

**Comment by lyiton** [comment]
> I haven't seen this myself - is it possible the S3 access key has been blocked?

Probably not, my tablet can still synchronize normally, only the mobile phone and Windows cannot synchronize. I checked whether it is connected and it still prompts that the corresponding bucket can be accessed.

> I found this [thread](https://stackoverflow.com/questions/26691286/amazon-s3-bucket-returning-403-forbidden) that suggests clock skew could be a factor in 403 errors with S3. Is your computer's clock time set automatically?

Of course it is set automatically.

**Comment by sboesen** [comment]
That is odd. Do all of your devices uses the same keys, and they can all sync on the same network? Do you have a VPN or something perhaps?

Definitely seems like that would indicate something odd with Remotely Sync.

**Comment by kadisonm** [comment]
> By the way, the status bar is always at (3/3).

![Obsidian_fm9RGK46Bu](https://github.com/sboesen/remotely-sync/assets/134670047/77ff943d-493b-4d49-a6cb-78c8cb3ee6ec)

I'm having a similar issue with my vault where the status bar is stuck. Not sure if there is an issue for this open or if it relates to one already.

**Comment by lyiton** [comment]
> > By the way, the status bar is always at (3/3).
> 
> ![Obsidian_fm9RGK46Bu](https://private-user-images.githubusercontent.com/134670047/290069912-77ff943d-493b-4d49-a6cb-78c8cb3ee6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDAxMjcsIm5iZiI6MTcwMjQzOTgyNywicGF0aCI6Ii8xMzQ2NzAwNDcvMjkwMDY5OTEyLTc3ZmY5NDNkLTQ5M2ItNGQ0OS1hNmNiLTc4YzhjYjNlZTZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMzU3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDExOGQ5YzZlZDljMzZmZDY0YzNjYmFkMzNiYjk0YTMxMmU2MGQzYjFmNzU3ZmU4ZDU4ODllYTBhZTZlM2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kGgPEKs0MCstV0n1FjTEH0FsKrsqqg8qwCQAYZjEkC0)
> 
> I'm having a similar issue with my vault where the status bar is stuck. Not sure if there is an issue for this open or if it relates to one already.

I checked my file on the bucket, but it wasn't actually uploaded. What about yours?

**Comment by kadisonm** [comment]
I screenshotted that a couple days ago but didn't get to making an issue. Also note that I found this on the initial sync.

Trying again I'm finding that it is showing the syncing in groups and then switching to (841/846) and getting stuck there. Once sync ends it goes back to showing the last synced.

![kz97Xp6al2](https://github.com/sboesen/remotely-sync/assets/134670047/bd1a0749-d382-46e7-a648-575483ff673d)
*Gif of it happening. (gif ends when it gets to (841/846))*

The files are syncing to my OneDrive though. which I can see on the OneDrive and in the Obsidian console. 

For me syncing new files works perfectly fine on the status bar, but I have found that adding new files without content shows them syncing in the status bar and the console, but they don't show up on the cloud. Deleting the no content files then syncing shows that it is trying to sync their deletion history "uploadLocalDelHistToRemote" If I sync again after it tries to sync them under "keepRemoteDelHist" and does this every consequent sync.

**Comment by sboesen** [comment]
Can you please try 0.4.28? I broke uploading the metadata file on S3 & Dropbox, fixed in 0.4.28 (#63).

**Comment by lyiton** [comment]
It still occurs in version 0.4.28.
![IMG_20231213_133035](https://github.com/sboesen/remotely-sync/assets/76651858/bc5a0a49-b40e-4984-aa48-fcc760a1cb4e)

**Comment by sboesen** [comment]
Attempted to undo the upload change in case the extra metadata field is resulting in an error. If it's possible, could you either 1) download the beta update 0.4.29 manually or 2) use [BRAT](https://github.com/sboesen/remotely-sync?tab=readme-ov-file#download-and-install) to install the latest version by specifying https://github.com/sboesen/remotely-sync

This will help test to see if the latest changes are affecting the upload error here.

**Comment by sboesen** [comment]
> ### Initial sync status bar stuck
> I screenshotted that a couple days ago but didn't get to making an issue.
> 
> Trying again I'm finding that it is showing the syncing in groups and then switching to (841/846) and getting stuck there. Once sync ends it goes back to showing the last synced.
> 
> ![kz97Xp6al2](https://private-user-images.githubusercontent.com/134670047/290072663-bd1a0749-d382-46e7-a648-575483ff673d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTAxMzEsIm5iZiI6MTcwMjQ0OTgzMSwicGF0aCI6Ii8xMzQ2NzAwNDcvMjkwMDcyNjYzLWJkMWEwNzQ5LWQzODItNDZlNy1hNjQ4LTU3NTQ4M2ZmNjczZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjkyMTA0YjJkZjU2MWVjYTVlMjlkOGNmYmIxMGJmZWZlMDViMDhjOGU5ZWQ3YzlmZGQ3OTc3ZGVhMDk2OTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOLPbuaYKT7bT571aUk2_L6xuYyaK6P0wW4YpKPLl90) [ ![kz97Xp6al2](https://private-user-images.githubusercontent.com/134670047/290072663-bd1a0749-d382-46e7-a648-575483ff673d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTAxMzEsIm5iZiI6MTcwMjQ0OTgzMSwicGF0aCI6Ii8xMzQ2NzAwNDcvMjkwMDcyNjYzLWJkMWEwNzQ5LWQzODItNDZlNy1hNjQ4LTU3NTQ4M2ZmNjczZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjkyMTA0YjJkZjU2MWVjYTVlMjlkOGNmYmIxMGJmZWZlMDViMDhjOGU5ZWQ3YzlmZGQ3OTc3ZGVhMDk2OTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOLPbuaYKT7bT571aUk2_L6xuYyaK6P0wW4YpKPLl90) ](https://private-user-images.githubusercontent.com/134670047/290072663-bd1a0749-d382-46e7-a648-575483ff673d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTAxMzEsIm5iZiI6MTcwMjQ0OTgzMSwicGF0aCI6Ii8xMzQ2NzAwNDcvMjkwMDcyNjYzLWJkMWEwNzQ5LWQzODItNDZlNy1hNjQ4LTU3NTQ4M2ZmNjczZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjkyMTA0YjJkZjU2MWVjYTVlMjlkOGNmYmIxMGJmZWZlMDViMDhjOGU5ZWQ3YzlmZGQ3OTc3ZGVhMDk2OTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOLPbuaYKT7bT571aUk2_L6xuYyaK6P0wW4YpKPLl90) [ ](https://private-user-images.githubusercontent.com/134670047/290072663-bd1a0749-d382-46e7-a648-575483ff673d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTAxMzEsIm5iZiI6MTcwMjQ0OTgzMSwicGF0aCI6Ii8xMzQ2NzAwNDcvMjkwMDcyNjYzLWJkMWEwNzQ5LWQzODItNDZlNy1hNjQ4LTU3NTQ4M2ZmNjczZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNjQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjkyMTA0YjJkZjU2MWVjYTVlMjlkOGNmYmIxMGJmZWZlMDViMDhjOGU5ZWQ3YzlmZGQ3OTc3ZGVhMDk2OTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOLPbuaYKT7bT571aUk2_L6xuYyaK6P0wW4YpKPLl90) _Gif of it happening. (gif ends when it gets to (841/846))_
> 
> The files are syncing to my OneDrive though, which I can see on the OneDrive and in the Obsidian console.
> 
> ### Syncing new files not uploading
> For me syncing new files works perfectly fine on the status bar, but I have found that adding new files without content shows them syncing in the status bar and the console, but they don't show up on the cloud. Deleting the no content files then syncing shows that it is trying to sync their deletion history "uploadLocalDelHistToRemote" If I sync again after it tries to sync them under "keepRemoteDelHist" and does this every consequent sync.
> 
> Edit: I just added headings to make it a bit more clear, these might be seperate issues but I found them together.

These are separate if you're not getting a 403 using S3  - I haven't touched OneDrive in the latest few updates

**Comment by lyiton** [comment]
> Attempted to undo the upload change in case the extra metadata field is resulting in an error. If it's possible, could you either 1) download the beta update 0.4.29 manually or 2) use [BRAT](https://github.com/sboesen/remotely-sync?tab=readme-ov-file#download-and-install) to install the latest version by specifying https://github.com/sboesen/remotely-sync
> 
> This will help test to see if the latest changes are affecting the upload error here.

![PixPin_2023-12-13_14-50-06](https://github.com/sboesen/remotely-sync/assets/76651858/9b04dacd-61c4-47c3-95b3-9dd28dd46c07)
After I manually installed version 0.4.29, I reopened obsidian and the automatic synchronization was successful immediately.

**Comment by sboesen** [comment]
Glad to hear! But that is very odd. Are you using AWS S3 or another cloud provider?

Seems like they don't like the metadata field. Maybe I can make it an option

**Comment by lyiton** [comment]
The cloud provider I use is Alibaba Cloud (China).

**Comment by sboesen** [comment]
Thanks - but now I'm not sure because you mentioned it was working on other devices. Seems odd, but will make it a configurable option until I can figure it out. Will mean not benefiting from #60 changes until then

**Comment by lyiton** [comment]
Sorry, I just rechecked my tablet device and updated it to 0.4.28. I found that the tablet is no longer working, and the prompt is the same as the mobile phone.
![PixPin_2023-12-13_15-19-43](https://github.com/sboesen/remotely-sync/assets/76651858/d5a7f836-4bcd-4305-a293-c03b23b98588)

**Comment by sboesen** [comment]
Ah that makes sense, thank you!

I looked at the documentation and it looks like Alibaba Cloud [differs in how metadata is uploaded](https://www.alibabacloud.com/help/en/oss/developer-reference/putobject#reference-l5p-ftw-tdb) for S3 objects - there is a header `x-oss-meta-` we must include and it probably does not like the metadata field as part of PutObject in the AWS S3 format. I'll add the option to disable for now and can explore adding direct support for Alibaba Cloud assuming I can't add the header easily to all requests (other S3 providers will probably ignore the header...)

**Comment by kadisonm** [comment]
> These are separate if you're not getting a 403 using S3 - I haven't touched OneDrive in the latest few updates

I'll move it into a seperate issue. How about the status bar being stuck?

**Comment by sboesen** [comment]
@kadisonm is it getting stuck on a large file? Could be related to https://github.com/sboesen/remotely-sync/issues/42. If not I suggest another separate issue, thank you!

**Comment by kadisonm** [comment]
I'm not entirely sure how to check since it still completes the sync then returns the sync status back to normal. While it is stuck I can see it still syncing files in the console as well, it just seems like it's not updating properly. My vault is also only 100mb and the largest file is roughly 2.5mb. Let me know if I should make a new issue or not.

**Comment by sboesen** [comment]
Make an issue! Sounds unique

**Comment by sboesen** [comment]
Still need to test 1dbdf87 but basically done

**Comment by sboesen** [comment]
Option to disable metadata sync added in 0.4.30, please reopen if it isn't working for you! Thanks for the details & translation PR :)

**Comment by lyiton** [comment]
It will be better if you can add notes for Alibaba Cloud in readme. Thank you!

**Comment by sboesen** [comment]
Good idea, added a section (temporarily). Will remove it once I implement #70 as it uses the S3 sync and we can implement a generic solution for syncing modification time to the remote storage provider.

**Comment by goldsmith9702** [comment]
> Ah that makes sense, thank you!
> 
> I looked at the documentation and it looks like Alibaba Cloud [differs in how metadata is uploaded](https://www.alibabacloud.com/help/en/oss/developer-reference/putobject#reference-l5p-ftw-tdb) for S3 objects - there is a header `x-oss-meta-` we must include and it probably does not like the metadata field as part of PutObject in the AWS S3 format. I'll add the option to disable for now and can explore adding direct support for Alibaba Cloud assuming I can't add the header easily to all requests (other S3 providers will probably ignore the header...)

The issue also can be reproduced when i use another Chinese cloud provider - Tencent Cloud (China)(Chinese name is 腾讯云). 

I'm not a developer. Here is the documentation  [PUT Object ](https://www.tencentcloud.com/document/product/436/7749) of Tencent Cloud for your further reference. 

After I set the option **Disable S3 metadata sync** on, I can sync data with Tencent Cloud normally.
